### ISSUE TITLE
[bug] Compare throwing not git repository error

### ISSUE THREAD

**Issue by DntPullALockett** [namolnad/Finch#136]
**Describe the bug**
Keep getting fatal: not a git repository: when trying to do a compare. I am testing this currently in a sample project. It could be that I do it have it setup properly.

**To Reproduce**
1.  Install finch using the brew method
2. Create the .finch folder and config using the template
3. Run the compare between two versions

**Expected behavior**
A changelog should be generated

**Screenshots**
<img width="906" alt="Screenshot 2023-06-27 at 8 48 57 AM" src="https://github.com/namolnad/Finch/assets/51751780/b7b728f5-6a21-4def-ab5c-bd430b5d72d0">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.4

**Additional context**

Config:

format:
  format_string: ' - << message >> - << commit_type_hyperlink >>'
  section_infos:
  - capitalizes_message: true
    tags:
    - feature
    title: Features
  - capitalizes_message: true
    tags:
    - bug
    title: Bug Fixes
  - capitalizes_message: true
    tags:
    - cleanup
  - capitalizes_message: true
    tags:
    - refactor

git:
  repo_base_url: {{REPO_URL}}
resolution_commands:
  build_number: /usr/bin/env bash -c 'git -C $PROJECT_DIR rev-list $NEW_VERSION --count'

**Comment by DntPullALockett** [comment]
Got it to work, had to move ,.finch into the .git directory. Is this correct?

**Comment by DntPullALockett** [comment]
Figured it out!

**Comment by namolnad** [comment]
Thanks @DntPullALockett, realizing that I've been missing GitHub notifications for a bit. Glad you got it figured out!
